version: '3.8'

services:
  validation-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SERVICE_NAME=ai-output-validator
      - SERVICE_VERSION=0.1.0
      - ENVIRONMENT=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AUTH_ENABLED=false
      - API_KEY=dev_test_key
      - LOG_LEVEL=DEBUG
    volumes:
      - ./app:/app/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s 